name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Specs
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    strategy:
      matrix:
        ruby: 
          - 2.7
          - "3.0"
          - 3.1
          - 3.2
        gemfile:
         - gemfiles/rails5.0.gemfile
         - gemfiles/rails5.2.gemfile
         - gemfiles/rails6.0.gemfile
         - gemfiles/rails7.0.gemfile
        exclude:
         - ruby: "3.0"
           gemfile: gemfiles/rails5.0.gemfile
         - ruby: "3.0"
           gemfile: gemfiles/rails5.2.gemfile
         - ruby: 3.1
           gemfile: gemfiles/rails5.0.gemfile
         - ruby: 3.1
           gemfile: gemfiles/rails5.2.gemfile
         - ruby: 3.1
           gemfile: gemfiles/rails6.0.gemfile
         - ruby: 3.2
           gemfile: gemfiles/rails5.0.gemfile
         - ruby: 3.2
           gemfile: gemfiles/rails5.2.gemfile
         - ruby: 3.2
           gemfile: gemfiles/rails6.0.gemfile

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
